version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: "%(asctime)s (%(name)s) [%(levelname)s] %(message)s"

filters:
  require_debug_true:
    (): devourer.utils.log.RequireDebugTrue

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    filters:
      - require_debug_true

loggers:
  devourer:
    level: DEBUG
    handlers:
      - console
