version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.8
      - image: circleci/redis:alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements/ci.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install Requirements
          command: |
            python -m venv ../venv
            . ../venv/bin/activate
            pip install -r requirements/ci.txt
      - save_cache:
          paths:
            - ../venv
          key: v1-dependencies-{{ checksum "requirements/ci.txt" }}
      - run:
          name: Python Version
          command: python -V
      - run:
          name: Tests
          when: always
          environment:
            REDIS_HOST: localhost
            REDIS_PORT: 6379
            GCP_PROJECT_ID: vis-devourer-test
            GCP_PUBSUB_PUBLIC_TOPIC: vis-devourer-test
            LOG_CONFIG_FILENAME: local.yml
            SENTRY_DSN:
          command: |
            . ../venv/bin/activate
            python -m pytest \
              --pylama \
              --junitxml=../tests_artifacts/junit.xml \
              --cov=. --cov-report=xml:../tests_artifacts/coverage.xml --cov-report=html:../tests_artifacts/coverage/ \
              .
      - store_test_results:
          path: ../tests_artifacts/
          destination: tests_artifacts
      - store_artifacts:
          path: ../tests_artifacts/
          destination: tests_artifacts


workflows:
  version: 2

  devourer:
    jobs:
      - test
