name: VIS Devourer

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379/tcp

    steps:
      - uses: actions/checkout@v1
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Cache requirements
        uses: actions/cache@v1
        id: cache-requirements
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/ci.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install requirements
        if: steps.cache-requirements.output.cache-hit != 'true'
        run: |
          python -m pip install -U pip
          pip install -r requirements/ci.txt
      - name: Python version
        run: python -V
      - name: Tests
        env:
          REDIS_HOST: localhost
          REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
          LOG_CONFIG_FILENAME: local.yml
        run: |
          python -m pytest --pylama --cov=. --cov-report term --cov-report html:../tests_artifacts/cov_html .
      - name: Test Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: test-artifacts
          path: ../tests_artifacts
