name: VIS Devourer

on: [push, pull_request]

jobs:

  test:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379/tcp

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache requirements
        uses: actions/cache@v2
        id: cache-requirements
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/ci.txt') }}
      - name: Install requirements
        if: steps.cache-requirements.output.cache-hit != 'true'
        run: |
          python -m pip install -U pip
          pip install -r requirements/ci.txt
      - name: Python version
        run: python -V
      - name: Tests
        env:
          REDIS_HOST: localhost
          REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
          GCP_PROJECT_ID: vis-devourer-test
          GCP_PUBSUB_PUBLIC_TOPIC: vis-devourer-test
          LOG_CONFIG_FILENAME: local.yml
          SENTRY_DSN:
          CELERY_BROKER_URL: redis://localhost:${{ job.services.redis.ports['6379'] }}/1
          CELERY_RESULT_BACKEND: redis://localhost:${{ job.services.redis.ports['6379'] }}/1
          CELERY_TASK_ALWAYS_EAGER: on
        run: |
          python -m pytest \
              --pylama --bandit \
              --junitxml=tests_results/junit.xml \
              --cov=. --cov-report=xml:tests_results/coverage.xml --cov-report=html:tests_results/coverage/ \
              devourer/
      - name: Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: tests_results/
